### ISSUE TITLE
Queue Privacy

### ISSUE THREAD

**Issue by bloops** [tdrhq/opc#2]
When queue_privacy is set to true, the current behaviour for a non-admin user is to show a blank queue in both the 'queue status' and 'my submissions'! The intended behaviour seems to be to show only the logged-in user's submissions in both 'queue status' and 'my submissions'. A small change in the code achieves this. (was probably a typo)

However, I think it is more sensible if we deny the queue display altogether when the contest is running. The same is done to the rankings page currently - it shows a message "You cannot view this page because of a privacy setting". Are there any other alternatives?

Maybe after the results are out, the queue could become public again. This would serve the additional utility of viewing other contestants' submissions. Adding a contestResultsTime variable (time when contest results are declared) would help implement this behaviour. Btw, contestResultsTime will also serve to withhold the scores until the test data is checked.

**Comment by tdrhq** [comment]
I think "My Submissions" page is still useful, since users need a way of seeing their previous submissions and previous results. (And it also serves as a very useful backup service :) ) Please go ahead and fix the behavior.

**Comment by bloops** [comment]
Fixed it. Now queue says 'you cannot ... privacy setting', and queue/mine works as usual.
